In [1]:
import numpy as np

In [8]:
## accessing Array Elements
arr1=([1,2,3,4,5])
print(arr1[0])

1


In [5]:
arr1[3]

np.int64(4)

In [9]:
arr3=np.array([1,2,3,4,5,6,7])
print(arr3[1:3])

[2 3]


In [12]:
print(arr3[-5:-2])

[3 4 5]


In [4]:
arr4=np.array([[1,2,3,4],[5,6,7,8]])
print(arr4.shape)

(2, 4)


In [6]:
import numpy as np
arr6=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr7=arr6.reshape(3,4)
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
## Numpy Joining array
arr1=np.array([123])
arr2= np.array ([456])
arr= np.concatenate ((arr1,arr2))
print(arr)
    

[123 456]


In [5]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
arr=np.array([1,2,3,4,5,6])
newar=np.array_split(arr,4)
print(newar)
             
            

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [38]:
## random numbers modul in range of (10000) 

from numpy import random
x=random.randint (10000)
print(x)

2770


In [54]:
##random number modul in float devision

from numpy import random
x=random.rand()
print(x)

0.6346772446687161


In [55]:
## generated random array
from numpy import random
x=random.randint(100,size=(5))
print(x)

[32 99 60 18 11]


In [56]:
## generated 2d randfdom array
from numpy import random 
x=random.randint(100,size=(3,4))
print(x)
                 

[[33 43 30 13]
 [24 73 13 82]
 [75 72  8 73]]


In [57]:
## generated a 1d array containing 5 random floats
from numpy import random
x=random.rand(5)
print(x)

[0.63706003 0.95733256 0.298324   0.06754947 0.42970106]


In [59]:
## generated a 2d array with 3 row each row containing 5 random numbers
from numpy import random
x=random.rand(3,5)
print(x)

[[0.69009086 0.69482615 0.68782643 0.27693204 0.37805691]
 [0.78631733 0.31806845 0.27141934 0.04541556 0.27829964]
 [0.17528331 0.44550074 0.37856799 0.34334338 0.20477467]]


In [2]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [3]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [6]:
arr_str=['merecedes','BMW','Audi','suzuki']

arr_num=[5,4,6,7,3]
np_arr_str=np.array(arr_str)
np_arr_num=np.array(arr_num)

print('numpy array (arr_str):',np_arr_str)
print('numpy array (arr_num):',np_arr_num)

numpy array (arr_str): ['merecedes' 'BMW' 'Audi' 'suzuki']
numpy array (arr_num): [5 4 6 7 3]


In [7]:
print('data type of arr_str:',type(arr_str))
print('data type of arr_num:',type(arr_num))

print('data type of np_arr_str:',type(np_arr_str))
print('data type of np_arr_num:',type(np_arr_num))


data type of arr_str: <class 'list'>
data type of arr_num: <class 'list'>
data type of np_arr_str: <class 'numpy.ndarray'>
data type of np_arr_num: <class 'numpy.ndarray'>


In [12]:
arr2=np.arange(start=0,stop=10)
print(arr2)


arr2=np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
matrix2=np.linspace(0,5)
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [3]:
matrix6=np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
print('sine function:',np.sin(4))
print('cosine funtion:',np.cos(4))
print('tan function:',np.tan(4))

sine function: -0.7568024953079282
cosine funtion: -0.6536436208636119
tan function: 1.1578212823495777


In [6]:
np.exp(2)

np.float64(7.38905609893065)

In [7]:
arr5=np.array([2,4,6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [8]:
np.log(2)

np.float64(0.6931471805599453)

In [9]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [10]:
np.log10(8)

np.float64(0.9030899869919435)

In [11]:
arr7=np.arange(1,6)
print('arr7:',arr7)

arr8=np.arange(3,8)
print('arr8:',arr8)

arr7: [1 2 3 4 5]
arr8: [3 4 5 6 7]


In [12]:
print('addition:',arr7+arr8)
print('subtraction:',arr7-arr8)
print('multiplication:',arr7*arr8)
print('division:',arr7/arr8)
print('power:',arr7**arr8)
print('inverse:',1/arr7)

addition: [ 4  6  8 10 12]
subtraction: [-2 -2 -2 -2 -2]
multiplication: [ 3  8 15 24 35]
division: [0.33333333 0.5        0.6        0.66666667 0.71428571]
power: [    1    16   243  4096 78125]
inverse: [1.         0.5        0.33333333 0.25       0.2       ]


In [14]:
matrix7=np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8=np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
